create table sensors(
                        id integer primary key generated by default as identity,
                        name varchar(30) unique,
                        created_at  timestamp,
                        created_who varchar
);

create table measurements(
                             id integer primary key generated by default as identity ,
                             sensor_id integer references sensors(id) on DELETE CASCADE ,
                             sensor_name varchar not null ,
                             value double precision not null check ( value > -100 and value < 100),
                             raining boolean not null,
                             measurement_date timestamp        not null
);